documents: app/src/**/*.{gql,ts,vue}
schema: api/src/generated/schema.graphql

extensions:
  codegen:
    generates:
      app/src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
  endpoints:
    default:
      url: http://localhost:3030/graphql
