documents: app/src/**/*.{ts,vue}
schema: api/src/generated/schema.graphql

extensions:
  codegen:
    generates:
      app/src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
  endpoints:
    default:
      url: http://localhost:3030/graphql
