services:
  os-api-db:
    image: postgres:12
    container_name: os-api-db
    environment:
      POSTGRES_DB: openskool
      POSTGRES_USER: openskool
      POSTGRES_PASSWORD: openskool
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - os-api-postgres:/var/lib/postgresql/data
    networks:
      - openskool

networks:
  openskool:
    name: openskool

volumes:
  os-api-postgres:
