// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompetencyList: typeof import('./../components/list/competency-list.vue')['default']
    CreateCompetencyFramework: typeof import('./../components/forms/create-competency-framework.vue')['default']
    CreateNestedCompetency: typeof import('./../components/forms/create-nested-competency.vue')['default']
    CreateRootCompetency: typeof import('./../components/forms/create-root-competency.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogDescription: typeof import('@headlessui/vue')['DialogDescription']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    FkListbox: typeof import('./../components/listbox/fk-listbox.vue')['default']
    LanguageSelect: typeof import('./../components/demo/language-select.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    RiArrowDownFill: typeof import('~icons/ri/arrow-down-fill')['default']
    RiArrowDropDownLine: typeof import('~icons/ri/arrow-drop-down-line')['default']
    RiArrowLeftSLine: typeof import('~icons/ri/arrow-left-s-line')['default']
    RiArrowUpFill: typeof import('~icons/ri/arrow-up-fill')['default']
    RiCheckFill: typeof import('~icons/ri/check-fill')['default']
    RiDeleteBinFill: typeof import('~icons/ri/delete-bin-fill')['default']
    RiEdit2Fill: typeof import('~icons/ri/edit2-fill')['default']
    RiEditBoxFill: typeof import('~icons/ri/edit-box-fill')['default']
    RiGlobalFill: typeof import('~icons/ri/global-fill')['default']
    RiLoaderFill: typeof import('~icons/ri/loader-fill')['default']
    RiPencilFill: typeof import('~icons/ri/pencil-fill')['default']
    RiShieldUserFill: typeof import('~icons/ri/shield-user-fill')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    UiBackbutton: typeof import('./../components/breadcrumb/ui-backbutton.vue')['default']
    UiBreadcrumb: typeof import('./../components/breadcrumb/ui-breadcrumb.vue')['default']
    UiDialog: typeof import('./../components/dialog/ui-dialog.vue')['default']
    UiIconButton: typeof import('./../components/button/ui-icon-button.vue')['default']
    UiListbox: typeof import('./../components/listbox/ui-listbox.vue')['default']
    UiListboxOption: typeof import('./../components/listbox/ui-listbox-option.vue')['default']
    UiMenu: typeof import('./../components/menu/ui-menu.vue')['default']
    UiMenuItem: typeof import('./../components/menu/ui-menu-item.vue')['default']
    UiMenuItemButton: typeof import('./../components/menu/ui-menu-item-button.vue')['default']
    UiSwitch: typeof import('./../components/switch/ui-switch.vue')['default']
    Unauthorized: typeof import('./../components/auth/unauthorized.vue')['default']
    UserSelect: typeof import('./../components/demo/user-select.vue')['default']
  }
}

export {}
