// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/hello-world.vue')['default']
    RiHome4Line: typeof import('~icons/ri/home4-line')['default']
  }
}

export { }
