// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/hello-world.vue')['default']
    RiCloseLine: typeof import('~icons/ri/close-line')['default']
    RiHome4Line: typeof import('~icons/ri/home4-line')['default']
    UiAlertDialog: typeof import('./components/ui/ui-alert-dialog.vue')['default']
    UiBackdrop: typeof import('./components/ui/ui-backdrop.vue')['default']
    UiDialog: typeof import('./components/ui/ui-dialog.vue')['default']
    UiVisuallyHidden: typeof import('./components/ui/ui-visually-hidden.vue')['default']
  }
}

export { }
