apiVersion: v1
kind: Service
metadata:
  labels:
    app: os-dev-auth
  name: os-dev-auth
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: os-dev-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: os-dev-auth
  name: os-dev-auth
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: os-dev-auth
  template:
    metadata:
      labels:
        app: os-dev-auth
    spec:
      containers:
        - env:
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db_password
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db_url
            - name: KC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: db_user
            - name: KC_HOSTNAME
              value: auth.dev2.openskool.dev
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: keycloak_admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: keycloak_admin_password
            - name: KC_PROXY
              value: edge
          image: registry.digitalocean.com/openskool/os-auth:19.0.1
          name: keycloak
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
