apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: os-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: 'dev.openskool.dev'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: os-dev-app
                port:
                  number: 80
    - host: 'api.dev.openskool.dev'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: os-dev-api
                port:
                  number: 80
    - host: 'auth.dev.openskool.dev'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: os-dev-auth
                port:
                  number: 80
    - host: 'turbo.openskool.dev'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: os-dx-turbo
                port:
                  number: 80
  tls:
    - hosts:
        - dev.openskool.dev
        - api.dev.openskool.dev
        - auth.dev.openskool.dev
        - turbo.openskool.dev
      secretName: os-tls
