name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          cache: yarn
          node-version: 16.8

      - name: Yarn
        run: |
          yarn install --immutable
          yarn workspace @os/api run bootstrap
          yarn run build
          yarn turbo run lint test
