name: Test

on:
  push:
    branches:
      - '*'
      - '!infrastructure'

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    concurrency: ${{ github.workflow }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: '.nvmrc'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        env:
          CERT: ${{ secrets.API_TEST_DATABASE_CERTIFICATE }}
          DATABASE_URL: ${{ secrets.API_TEST_DATABASE_URL }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_REMOTE_ONLY: true
        run: |
          echo "$CERT" | base64 --decode > ./test-db.cert
          export DATABASE_URL="${DATABASE_URL}&sslcert=$(pwd)/test-db.cert"
          pnpm --filter api exec prisma db push --accept-data-loss
          pnpm exec turbo run lint test

      - name: Api Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Api Tests
          path: api/test.xml
          reporter: java-junit

      - name: App Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: App Tests
          path: app/test.xml
          reporter: java-junit
